const WHATSAPP_NUMBER = "213697454244";
const products = [
{id:1,name:"سنيكرز أبيض Urban",price:4800,oldPrice:5600,stock:8,sizes:[39,40,41,42,43],colors:["أبيض","أسود"],badge:"الأكثر مبيعًا",image:"https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=1000",desc:"سنيكرز عصري بتصميم نظيف ومريح، مناسب للإطلالات اليومية.",material:"جلد صناعي عالي الجودة · نعل مرن",comfort:"خفيف ومريح للمشي اليومي"},
{id:2,name:"سنيكرز أبيض Classic",price:5200,stock:6,sizes:[40,41,42,43,44],colors:["أبيض"],badge:"جديد",image:"https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=1000",desc:"تصميم كلاسيكي أنيق يجمع بين البساطة والراحة.",material:"خامة متينة · بطانة مريحة",comfort:"راحة طوال اليوم"},
{id:3,name:"حذاء نسائي Fashion",price:4500,oldPrice:5100,stock:7,sizes:[36,37,38,39,40],colors:["أبيض","بيج"],badge:"عرض",image:"https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=1000",desc:"حذاء نسائي أنيق بإطلالة عصرية للاستخدام اليومي والخروج.",material:"خامة ناعمة · تشطيب أنيق",comfort:"خفيف وسهل الارتداء"},
{id:4,name:"حذاء رياضي Black",price:5500,stock:5,sizes:[40,41,42,43,44],colors:["أسود"],badge:"اختيار NESAQO",image:"https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=1000",desc:"موديل رياضي أسود بتصميم عملي ومظهر قوي.",material:"شبك تنفسي · نعل مطاطي",comfort:"تهوية جيدة وثبات أثناء الحركة"},
{id:5,name:"سنيكرز Red Street",price:5000,oldPrice:5800,stock:9,sizes:[39,40,41,42,43],colors:["أحمر","أبيض"],badge:"ترند",image:"https://images.unsplash.com/photo-1543508282-6319a3e2621f?w=1000",desc:"سنيكرز شبابي بلمسة جريئة وتفاصيل رياضية مميزة.",material:"خامة قوية · نعل مرن",comfort:"مصمم للحركة اليومية"},
{id:6,name:"حذاء نسائي Elegant",price:5900,oldPrice:6900,stock:4,sizes:[36,37,38,39],colors:["أسود","بيج"],badge:"الأكثر أناقة",image:"https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=1000",desc:"تصميم نسائي أنيق يمنح الإطلالة لمسة راقية.",material:"خامة أنيقة · تشطيب دقيق",comfort:"بطانة ناعمة لراحة أفضل"},
{id:7,name:"سنيكرز Premium",price:6200,stock:6,sizes:[40,41,42,43,44],colors:["أبيض","رمادي"],badge:"Premium",image:"https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=1000",desc:"سنيكرز بمظهر فاخر وتفاصيل عصرية لمن يبحث عن التميز.",material:"خامة Premium · نعل عالي المرونة",comfort:"دعم جيد للقدم أثناء المشي"},
{id:8,name:"حذاء رياضي Light",price:4700,oldPrice:5300,stock:10,sizes:[39,40,41,42,43,44],colors:["أسود","أبيض"],badge:"خفيف",image:"https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=1000",desc:"موديل خفيف وعملي، مناسب للمشي والاستعمال اليومي.",material:"نسيج خفيف · نعل مرن",comfort:"خفيف جدًا ومرن"}
];
let cart=JSON.parse(localStorage.getItem("nesaqo_cart")||"[]");
const $=id=>document.getElementById(id), productsGrid=$("productsGrid"),searchInput=$("searchInput"),cartCount=$("cartCount"),cartItems=$("cartItems"),cartTotal=$("cartTotal"),cartDrawer=$("cartDrawer"),overlay=$("overlay"),orderModal=$("orderModal"),productModal=$("productModal"),productDetails=$("productDetails");
const money=v=>new Intl.NumberFormat("ar-DZ").format(v)+" دج";
const discount=p=>p.oldPrice?Math.round((1-p.price/p.oldPrice)*100):0;
function renderProducts(list=products){productsGrid.innerHTML=list.map(p=>`<article class="product-card"><div class="image-wrap"><img class="product-image" src="${p.image}" alt="${p.name}" loading="lazy"><div class="badges">${p.badge?`<span class="product-badge">${p.badge}</span>`:""}${p.oldPrice?`<span class="discount-badge">-${discount(p)}%</span>`:""}</div></div><div class="product-info"><div class="rating">★★★★★ <span>تقييمات لاحقًا</span></div><h3 class="product-title">${p.name}</h3><div class="price-line"><strong class="price">${money(p.price)}</strong>${p.oldPrice?`<del>${money(p.oldPrice)}</del>`:""}</div><div class="sizes-preview"><b>المقاسات:</b> ${p.sizes.join(" · ")}</div><div class="colors-preview"><b>الألوان:</b> ${p.colors.join(" · ")}</div><div class="product-actions"><button class="secondary-btn" onclick="showProduct(${p.id})">التفاصيل</button><button class="primary-btn" onclick="showProduct(${p.id})">أضف إلى السلة</button></div></div></article>`).join("")}
function showProduct(id){const p=products.find(x=>x.id===id);productDetails.innerHTML=`<img class="detail-image" src="${p.image}" alt="${p.name}"><span class="eyebrow">${p.badge||"NESAQO COLLECTION"}</span><h2>${p.name}</h2><div class="rating detail-rating">★★★★★ <span>تقييمات الزبائن قريبًا</span></div><div class="price-line detail-price-line"><strong class="detail-price">${money(p.price)}</strong>${p.oldPrice?`<del>${money(p.oldPrice)}</del><span class="discount-text">خصم ${discount(p)}%</span>`:""}</div><p class="muted">${p.desc}</p><div class="specs"><div><b>الخامة</b><span>${p.material}</span></div><div><b>الراحة</b><span>${p.comfort}</span></div><div><b>التوصيل</b><span>للمنزل أو مكتب الشحن</span></div></div><div class="choice-group"><strong>اختر اللون</strong><div class="choice-row">${p.colors.map((c,i)=>`<button class="color-btn ${i===0?"selected":""}" data-color="${c}" onclick="selectChoice(this,'.color-btn')">${c}</button>`).join("")}</div></div><div class="choice-group"><strong>اختر المقاس</strong><div class="choice-row">${p.sizes.map(s=>`<button class="size-btn" data-size="${s}" onclick="selectChoice(this,'.size-btn')">${s}</button>`).join("")}</div></div><button class="primary-btn full detail-buy" onclick="addDetailToCart(${p.id})">إضافة إلى السلة</button>`;productModal.classList.add("show");overlay.classList.add("show")}
function selectChoice(btn,selector){document.querySelectorAll(selector).forEach(x=>x.classList.remove("selected"));btn.classList.add("selected")}
function addDetailToCart(id){const size=document.querySelector(".size-btn.selected")?.dataset.size;if(!size){alert("يرجى اختيار المقاس.");return}const color=document.querySelector(".color-btn.selected")?.dataset.color;addToCart(id,Number(size),color);closeProductModal();openCart()}
function addToCart(id,size,color){const p=products.find(x=>x.id===id),item=cart.find(x=>x.id===id&&x.size===size&&x.color===color);if(item)item.qty=Math.min(item.qty+1,p.stock);else cart.push({id,qty:1,size,color});saveCart()}
function saveCart(){localStorage.setItem("nesaqo_cart",JSON.stringify(cart));renderCart()}
function removeFromCart(id,size,color){cart=cart.filter(x=>!(x.id===id&&x.size===size&&x.color===color));saveCart()}
function changeQty(id,size,color,n){const item=cart.find(x=>x.id===id&&x.size===size&&x.color===color),p=products.find(x=>x.id===id);if(!item)return;item.qty+=n;if(item.qty<=0)removeFromCart(id,size,color);else{item.qty=Math.min(item.qty,p.stock);saveCart()}}
function renderCart(){const count=cart.reduce((s,x)=>s+x.qty,0),total=cart.reduce((s,x)=>{const p=products.find(y=>y.id===x.id);return s+p.price*x.qty},0);cartCount.textContent=count;cartTotal.textContent=money(total);cartItems.innerHTML=cart.length?cart.map(i=>{const p=products.find(x=>x.id===i.id);return `<div class="cart-item"><img src="${p.image}" alt="${p.name}"><div><h3>${p.name}</h3><p>${i.color||""} · المقاس ${i.size}</p><strong>${money(p.price*i.qty)}</strong><div class="qty"><button onclick="changeQty(${p.id},${i.size},'${i.color||""}',-1)">−</button><span>${i.qty}</span><button onclick="changeQty(${p.id},${i.size},'${i.color||""}',1)">+</button></div></div><button class="icon-btn" onclick="removeFromCart(${p.id},${i.size},'${i.color||""}')">🗑</button></div>`}).join(""):"<div class='empty'>السلة فارغة حاليًا 🛒</div>"}
function openCart(){cartDrawer.classList.add("open");overlay.classList.add("show")}function closeCart(){cartDrawer.classList.remove("open");if(!orderModal.classList.contains("show")&&!productModal.classList.contains("show"))overlay.classList.remove("show")}function closeProductModal(){productModal.classList.remove("show");if(!cartDrawer.classList.contains("open")&&!orderModal.classList.contains("show"))overlay.classList.remove("show")}function openOrderModal(){if(!cart.length)return openCart();cartDrawer.classList.remove("open");orderModal.classList.add("show");overlay.classList.add("show")}function closeOrderModal(){orderModal.classList.remove("show");if(!cartDrawer.classList.contains("open")&&!productModal.classList.contains("show"))overlay.classList.remove("show")}
function buildWhatsAppMessage(){const name=$("fullName").value.trim(),phone=$("phone").value.trim(),address=$("address").value.trim(),type=document.querySelector('input[name="deliveryType"]:checked')?.value||"",da=$("deliveryAddress").value.trim(),notes=$("notes").value.trim();let m="مرحباً، أريد تأكيد طلب من متجر NESAQO STORE:\n\n";cart.forEach((i,n)=>{const p=products.find(x=>x.id===i.id);m+=`${n+1}. ${p.name} — ${i.color||""} — المقاس ${i.size} × ${i.qty} — ${money(p.price*i.qty)}\n`});const total=cart.reduce((s,i)=>s+products.find(p=>p.id===i.id).price*i.qty,0);m+=`\n💰 المجموع: ${money(total)}\n👤 الاسم: ${name}\n📞 الهاتف: ${phone}\n📍 الولاية/البلدية: ${address}\n🚚 التوصيل: ${type}\n📦 ${type==='باب المنزل'?'العنوان':'مكتب الشحن'}: ${da}`;if(notes)m+=`\n📝 ${notes}`;return m}
$("openCart").addEventListener("click",openCart);$("closeCart").addEventListener("click",closeCart);$("checkoutBtn").addEventListener("click",openOrderModal);$("closeModal").addEventListener("click",closeOrderModal);$("closeProductModal").addEventListener("click",closeProductModal);overlay.addEventListener("click",()=>{closeCart();closeOrderModal();closeProductModal()});searchInput.addEventListener("input",e=>{const q=e.target.value.toLowerCase();renderProducts(products.filter(p=>(p.name+p.desc+p.colors.join(" ")).toLowerCase().includes(q)))});$("orderForm").addEventListener("submit",e=>{e.preventDefault();if(!document.querySelector('input[name="deliveryType"]:checked'))return alert("يرجى اختيار طريقة التوصيل.");window.open(`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(buildWhatsAppMessage())}`,"_blank")});renderProducts();renderCart();
