const WHATSAPP_NUMBER="213697454244";
const productImages=[
"assets/ChatGPT Image 19 أغسطس 2026، 03_34_40 م.png","assets/ChatGPT Image 19 أغسطس 2026، 03_34_48 م.png","assets/ChatGPT Image 19 أغسطس 2026، 03_36_56 م.png","assets/ChatGPT Image 19 أغسطس 2026، 03_37_03 م.png","assets/ChatGPT Image 19 أغسطس 2026، 03_37_08 م.png","assets/ChatGPT Image 19 أغسطس 2026، 03_37_15 م.png","assets/ChatGPT Image 19 أغسطس 2026، 03_37_28 م.png","assets/ChatGPT Image 19 أغسطس 2026، 03_37_35 م.png","assets/ChatGPT Image 19 أغسطس 2026، 03_37_40 م.png","assets/ChatGPT Image 19 أغسطس 2026، 03_37_46 م.png","assets/ChatGPT Image 19 أغسطس 2026، 03_39_11 م.png","assets/ChatGPT Image 20 أغسطس 2026، 01_49_21 م.png","assets/ChatGPT Image 20 أغسطس 2026، 01_52_43 م.png","assets/ChatGPT Image 20 أغسطس 2026، 01_59_08 م.png"];
const prices=Array(14).fill(2000);
const badges=Array(14).fill("جديد");
const femaleIds=new Set([1,2,10,11,12,13,14]);
const products=productImages.map((image,index)=>({id:index+1,name:`NASAQO — موديل ${String(index+1).padStart(2,"0")}`,price:2000,stock:8,sizes:[36,37,38,39,40],colors:["كما في الصورة"],category:femaleIds.has(index+1)?"نسائية":"رجالية",badge:badges[index],image,desc:`حذاء ${femaleIds.has(index+1)?"نسائي":"رجالي"} من تشكيلة NASAQO، بتصميم أنيق للاستخدام اليومي.`,material:"خامة مختارة · نعل مرن",comfort:"مريح ومناسب للاستخدام اليومي"}));
let cart=JSON.parse(localStorage.getItem("nesaqo_cart")||"[]");const $=id=>document.getElementById(id),productsGrid=$("productsGrid"),searchInput=$("searchInput"),cartCount=$("cartCount"),cartItems=$("cartItems"),cartTotal=$("cartTotal"),cartDrawer=$("cartDrawer"),overlay=$("overlay"),orderModal=$("orderModal"),productModal=$("productModal"),productDetails=$("productDetails");const money=v=>new Intl.NumberFormat("ar-DZ").format(v)+" دج";
let activeCategory="all";
function renderProducts(list=products){productsGrid.innerHTML=list.map(p=>`<article class="product-card" data-category="${p.category}"><div class="image-wrap"><img class="product-image" src="${p.image}" alt="${p.name}" loading="lazy"><div class="badges"><span class="product-badge">${p.badge}</span><span class="category-badge">${p.category}</span></div></div><div class="product-info"><div class="rating">★★★★★ <span>تقييمات لاحقًا</span></div><h3 class="product-title">${p.name}</h3><div class="price-line"><strong class="price">${money(p.price)}</strong></div><div class="sizes-preview"><b>المقاسات:</b> ${p.sizes.join(" · ")}</div><div class="colors-preview"><b>اللون:</b> ${p.colors[0]}</div><div class="product-actions"><button class="secondary-btn" onclick="showProduct(${p.id})">التفاصيل</button><button class="primary-btn" onclick="showProduct(${p.id})">أضف إلى السلة</button></div></div></article>`).join("")}
function filterProducts(category){activeCategory=category;document.querySelectorAll("[data-category-filter]").forEach(b=>b.classList.toggle("active",b.dataset.categoryFilter===category));const q=searchInput.value.toLowerCase();renderProducts(products.filter(p=>(category==="all"||p.category===category)&&(`${p.name} ${p.category} ${p.desc} ${p.colors.join(" ")}`).toLowerCase().includes(q)))}
function showProduct(id){const p=products.find(x=>x.id===id);productDetails.innerHTML=`<img class="detail-image" src="${p.image}" alt="${p.name}"><span class="eyebrow">${p.category} · ${p.badge}</span><h2>${p.name}</h2><div class="rating detail-rating">★★★★★ <span>تقييمات الزبائن قريبًا</span></div><div class="price-line detail-price-line"><strong class="detail-price">${money(p.price)}</strong></div><p class="muted">${p.desc}</p><div class="specs"><div><b>التصنيف</b><span>${p.category}</span></div><div><b>الخامة</b><span>${p.material}</span></div><div><b>الراحة</b><span>${p.comfort}</span></div><div><b>التوصيل</b><span>للمنزل أو مكتب الشحن</span></div></div><div class="choice-group"><strong>اختر اللون</strong><div class="choice-row">${p.colors.map((c,i)=>`<button class="color-btn ${i===0?"selected":""}" data-color="${c}" onclick="selectChoice(this,'.color-btn')">${c}</button>`).join("")}</div></div><div class="choice-group"><strong>اختر المقاس</strong><div class="choice-row">${p.sizes.map(s=>`<button class="size-btn" data-size="${s}" onclick="selectChoice(this,'.size-btn')">${s}</button>`).join("")}</div></div><button class="primary-btn full detail-buy" onclick="addDetailToCart(${p.id})">إضافة إلى السلة</button>`;productModal.classList.add("show");overlay.classList.add("show")}
function selectChoice(btn,selector){document.querySelectorAll(selector).forEach(x=>x.classList.remove("selected"));btn.classList.add("selected")}
function addDetailToCart(id){const size=document.querySelector(".size-btn.selected")?.dataset.size;if(!size)return alert("يرجى اختيار المقاس.");const color=document.querySelector(".color-btn.selected")?.dataset.color;addToCart(id,Number(size),color);closeProductModal();openCart()}
function addToCart(id,size,color){const p=products.find(x=>x.id===id),item=cart.find(x=>x.id===id&&x.size===size&&x.color===color);if(item)item.qty=Math.min(item.qty+1,p.stock);else cart.push({id,qty:1,size,color});saveCart()}
function saveCart(){localStorage.setItem("nesaqo_cart",JSON.stringify(cart));renderCart()}
function removeFromCart(id,size,color){cart=cart.filter(x=>!(x.id===id&&x.size===size&&x.color===color));saveCart()}
function changeQty(id,size,color,n){const item=cart.find(x=>x.id===id&&x.size===size&&x.color===color),p=products.find(x=>x.id===id);if(!item)return;item.qty+=n;if(item.qty<=0)removeFromCart(id,size,color);else{item.qty=Math.min(item.qty,p.stock);saveCart()}}
function renderCart(){const count=cart.reduce((s,x)=>s+x.qty,0),total=cart.reduce((s,x)=>s+products.find(y=>y.id===x.id).price*x.qty,0);cartCount.textContent=count;cartTotal.textContent=money(total);cartItems.innerHTML=cart.length?cart.map(i=>{const p=products.find(x=>x.id===i.id);return `<div class="cart-item"><img src="${p.image}" alt="${p.name}"><div><h3>${p.name}</h3><p>${p.category} · ${i.color||""} · المقاس ${i.size}</p><strong>${money(p.price*i.qty)}</strong><div class="qty"><button onclick="changeQty(${p.id},${i.size},'${i.color||""}',-1)">−</button><span>${i.qty}</span><button onclick="changeQty(${p.id},${i.size},'${i.color||""}',1)">+</button></div></div><button class="icon-btn" onclick="removeFromCart(${p.id},${i.size},'${i.color||""}')">🗑</button></div>`}).join(""):"<div class='empty'>السلة فارغة حاليًا 🛒</div>"}
function openCart(){cartDrawer.classList.add("open");overlay.classList.add("show")}function closeCart(){cartDrawer.classList.remove("open");if(!orderModal.classList.contains("show")&&!productModal.classList.contains("show"))overlay.classList.remove("show")}function closeProductModal(){productModal.classList.remove("show");if(!cartDrawer.classList.contains("open")&&!orderModal.classList.contains("show"))overlay.classList.remove("show")}function openOrderModal(){if(!cart.length)return openCart();cartDrawer.classList.remove("open");orderModal.classList.add("show");overlay.classList.add("show")}function closeOrderModal(){orderModal.classList.remove("show");if(!cartDrawer.classList.contains("open")&&!productModal.classList.contains("show"))overlay.classList.remove("show")}
function buildWhatsAppMessage(){const name=$("fullName").value.trim(),phone=$("phone").value.trim(),address=$("address").value.trim(),type=document.querySelector('input[name="deliveryType"]:checked')?.value||"",da=$("deliveryAddress").value.trim(),notes=$("notes").value.trim();let m="مرحباً، أريد تأكيد طلب من متجر NASAQO STORE:\n\n";cart.forEach((i,n)=>{const p=products.find(x=>x.id===i.id);m+=`${n+1}. ${p.name} — ${p.category} — ${i.color||""} — المقاس ${i.size} × ${i.qty} — ${money(p.price*i.qty)}\n`});const total=cart.reduce((s,i)=>s+products.find(p=>p.id===i.id).price*i.qty,0);m+=`\n💰 المجموع: ${money(total)}\n👤 الاسم: ${name}\n📞 الهاتف: ${phone}\n📍 الولاية/البلدية: ${address}\n🚚 التوصيل: ${type}\n📦 ${type==='باب المنزل'?'العنوان':'مكتب الشحن'}: ${da}`;if(notes)m+=`\n📝 ${notes}`;return m}
$("openCart").addEventListener("click",openCart);$("closeCart").addEventListener("click",closeCart);$("checkoutBtn").addEventListener("click",openOrderModal);$("closeModal").addEventListener("click",closeOrderModal);$("closeProductModal").addEventListener("click",closeProductModal);overlay.addEventListener("click",()=>{closeCart();closeOrderModal();closeProductModal()});document.querySelectorAll("[data-category-filter]").forEach(b=>b.addEventListener("click",()=>filterProducts(b.dataset.categoryFilter)));searchInput.addEventListener("input",()=>filterProducts(activeCategory));$("orderForm").addEventListener("submit",e=>{e.preventDefault();if(!document.querySelector('input[name="deliveryType"]:checked'))return alert("يرجى اختيار طريقة التوصيل.");window.open(`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(buildWhatsAppMessage())}`,"_blank")});renderProducts();renderCart();